db:
  name: mysql
  pwd: 123456
redis:
  name: redis
spring:
  profiles:
    active: dev

---

spring:
  application:
    name: HotelSystemBackend
  datasource:
    url: jdbc:mysql://stillmind.top:3306/HotelSystem?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

---


spring:
  application:
    name: HotelSystemBackend
  datasource:
    url: jdbc:mysql://${db.name}:3306/take_out?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${db.pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${redis.name}
      port: 6379
  config:
    activate:
      on-profile: pro
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

---
